"""make last_used_at of apikey timezone aware

Revision ID: 84618f00916c
Revises: cb3546b2b1b8
Create Date: 2025-09-24 13:18:52.106513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.engine.reflection import Inspector
from langflow.utils import migration
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '84618f00916c'
down_revision: Union[str, None] = 'cb3546b2b1b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apikey', schema=None) as batch_op:
        batch_op.alter_column('last_used_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apikey', schema=None) as batch_op:
        batch_op.alter_column('last_used_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    # ### end Alembic commands ###
