ALTER TABLE flow
ALTER COLUMN updated_at TYPE TIMESTAMP WITH TIME ZONE
USING updated_at AT TIME ZONE 'UTC';

ALTER TABLE file
ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE
USING created_at AT TIME ZONE 'UTC';



ALTER TABLE "user"
ALTER COLUMN create_at TYPE TIMESTAMP WITH TIME ZONE
USING create_at AT TIME ZONE 'UTC';

ALTER TABLE "user"
ALTER COLUMN updated_at TYPE TIMESTAMP WITH TIME ZONE
USING updated_at AT TIME ZONE 'UTC';

ALTER TABLE "user"
ALTER COLUMN last_login_at TYPE TIMESTAMP WITH TIME ZONE
USING last_login_at AT TIME ZONE 'UTC';


ALTER TABLE message
ALTER COLUMN timestamp TYPE TIMESTAMP WITH TIME ZONE;


ALTER TABLE transaction
    ALTER COLUMN timestamp TYPE TIMESTAMP WITH TIME ZONE
    USING timestamp AT TIME ZONE 'UTC',
    ALTER COLUMN timestamp DROP NOT NULL; 